### PR TITLE
Fix https://github.com/totten/civix/issues/237

### PR DESCRIPTION
**Pull request by aydun**

### CODE REVIEW

**Comment by colemanw** [comment]
Cool. What do you think @totten?

**Comment by totten** [comment]
Nicely done @aydun!

I added a basic test case, and the patch appears to fix the ordering. (Expected ordering: `Flour` before `Bread`; `Bread` before `Sandwich`; `Sandwich` before`Meal`)

@michaelmcandrew originally wrote this algorithm, so he might have more thoughts on it. Let's wait a couple days to see if he's got feedback.

**Comment by aydun** [comment]
Nice!  Looks like there was more work required for the test than the fix!

**Comment by totten** [comment]
Cool, merging. Thanks all!

**Comment by totten** [comment]
Released in v22.07.0.

**Pull request merged**
